# -*- coding: utf-8 -*-
"""2220039.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtz8jelF_bNTMY7tGeMp9DA1mJNtLkbB
"""

from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# 1. Mengambil dataset dari UCI
dataset = fetch_ucirepo(id=17)

# 2. Ambil fitur (X) dan target (y)
X = dataset.data.features
y = dataset.data.targets

# Tambahan: Konversi target y ke dalam bentuk flat array agar scikit-learn tidak bingung
y = y.values.ravel()

# 3. Membagi data (80% latih, 20% uji)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Proses Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Selesai! Data berhasil dibagi dan discaling tanpa error.")

from sklearn.svm import SVC
import joblib

model = SVC(kernel='linear', probability=True)
model.fit(X_train_scaled, y_train)

# Simpan ke file
joblib.dump(model, 'model_cancer.pkl')
joblib.dump(scaler, 'scaler.pkl') # Simpan scaler agar input user nanti bisa disamakan skalanya
